### ISSUE TITLE
General slowness of tracking compared to 'native'

### ISSUE THREAD

**Issue by Fragilem17** [jonathanhart/oculus-ane#11]
I'm getting perfect 60 fps in away, but there seems to be some noticeable lag between head movement and the rendering of the 3D scene. Are you guys seeing the same thing? or is it something else i'm doing in the demo?

If not my implementation, where is the extra delay to be found? In other words, is it something that can be fixed? or will it never get better then this inside AIR?

**Comment by Fragilem17** [comment]
maybe it's just your head messing with you because of the missing barrel distortion.

**Comment by jonathanhart** [comment]
I'm thinking this is not the case, as it polls the current tracking
information every frame.

My original method was to send an FREDispatchAsyncEvent when the tracking
information was updated, but realized this could cause lag if there was any
queuing system in the way of the native context and the as3 context, so
that's why I adopted the per-frame polling, so that the native tracking
code would be forced inside the same stack and thread as as3 context...

I can't vouch for absolute sure that there is no lag introduced somewhere,
but I am thinking it is unlikely due to the extension. One thing that could
be happening is the framerate is dropping and then recovering at higher
than 60fps, which would average out to 60 but visually appear off.

Jonathan

**Comment by Fragilem17** [comment]
I get what you're saying, requesting and getting new tracking info each frame is not the problem probably.
It looks and feels like i'm running at 60 fps when just looking at my screen.
but inside the rift and shaking my head left and right i feel like it's lagging, it's smooth but just a tad to late.

What if everything is lagging?

I mean, the framerate is okay, the tracking is okay, everything is just a few frames behind... you know what i'm saying? 

Or again, maybe it's just because of the missing barrel shader messing with my head, looking up and down now can really make you sick.

PS: Been playing with awayBuilder, love it!

**Comment by Fragilem17** [comment]
Barrelshader looking pretty good to me now.. it's obvious there is a lag somewhere... could someone else confirm this on their system? Feels like everything is lagging at least 4 frames behind.

my specs:
core-i7-2600@3.4GHz
Geforce GTX 550 Ti

**Comment by Fragilem17** [comment]
Committed a new version where predictive tracking is enabled in the DLL. Much better results now! The next SDK is going to have even better prediction.
