### ISSUE TITLE
ANE Needs to be Updated to include Windows DLL

### ISSUE THREAD

**Issue by BigPhilCombo** [jonathanhart/oculus-ane#4]
I believe you need to modify the extension xml to support the windows platform and the newly added windows.dll

**Comment by Fragilem17** [comment]
trying to set up the windows project that was commited now.. there are some external dependencies that are not in the repo.. will add those and update the path's, once i can compile the dll's i'll try to build the ANE with windows support.  Great work pchertok!

**Comment by Fragilem17** [comment]
I've commited to my repo: https://github.com/Fragilem17/oculus-ane 
i've build the ANE, can compile but apart from an empty _extContext i get no public methods on my instance in flash.

I do see in the console that the DLL is being used, this is in the console.
"Initialized, Native Extension Initialized OVR ERROR: no Sensor found"

But that does not explain why the instance in flash has nothing of the methods that it should have. like isSupported, getHMDInfo and getCameraQuaternion.

maybe somebody can take a look at my repo? i feel bad sending a pull request to something that might not work.

the SLN has been updated to the free VS2012 express version (couldn't build otherwise)

**Comment by jonathanhart** [comment]
Someone else reported that the extension.xml has not been updated yet to
include the windows dll. Could this be related? Pretty swamped this week so
I haven't been able to help out much unfortunately.

**Comment by Fragilem17** [comment]
No fixed that, its included now. It might work, without a rift its hard to
test. :-)  just weird those public functions are not there.

**Comment by malDuffin** [comment]
The MSVCP110.DLL is still missing ( didn't realise when I put in our entry for the VR Jam )

Check out http://www.twitch.tv/cymaticbruce/b/454061680 ( go to 1:59:30 ), and see how he goes to run the Flare3D entry with the Oculus ANE.

Is it OK to ship this .DLL with the ANE?
